name: boobam
favicon: null
layout_spectrum: 0.5054675054270774
typography_spectrum: 0.7377215081360191
title: Eco Echo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2dacf'
    - '#a59b91'
    - '#131514'
    - '#645649'
    - '#36f68f'
  brandStrength: 0.1707058202009648
  lightness: 0.9252916353289038
  saturation: 0.8040710343047976
  rhythmicContrast: 0.49042040621861815
purpose: []
